version: "3.9"
services:

  joey_dev_appserver:
    image: joey/docker-springboot-app
    ports:
      - "8888:8080"
    restart: on-failure
    depends_on:
      - joey_dev_database_server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://joey_dev_database_server:5432/joeydbdev
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - joey_development_network
    volumes:
      - joey_application_volume:/var/lib/joey

  joey_prod_appserver:
    image: joey/docker-springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - joey_dev_database_server
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://joey_prod_database_server:5432/joeydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    networks:
      - joey_development_network
    volumes:
      - joey_application_volume:/var/lib/joey

  joey_prod_database_server:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=joeydb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - joey_development_network
    volumes:
      - joey_database_volume:/var/lib/postgres

  joey_dev_database_server:
    image: postgres:latest
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=joeydbdev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - joey_development_network
    volumes:
      - joey_database_volume:/var/lib/postgres

  joey_dev_database_admin:
    image: adminer:latest
    restart: always
    ports:
      - "9090:8080"
    networks:
      - joey_development_network

networks:
  joey_production_network:
  joey_development_network:


volumes:
  joey_database_volume: {}
  joey_application_volume: {}